name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  setmatrix:
    name: "Set the matrix"

    runs-on: "ubuntu-latest"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        # pl, ro, uk are missing
        run: |
          content=`cat data.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=matrix::$content"

  rev-check:
    name: "Revcheck"

    runs-on: "ubuntu-latest"
    needs: setmatrix

    strategy:
      matrix:
        language: ${{fromJSON(needs.setmatrix.outputs.matrix).languages}}

    steps:
      - name: "Checkout php/doc-base"
        uses: "actions/checkout@v2"
        with:
          path: "base"
          repository: "php/doc-base"

      - name: "Checkout php/doc-${{ matrix.language }}"
        uses: "actions/checkout@v2"
        with:
          path: "${{ matrix.language }}"
          repository: "php/doc-${{ matrix.language }}"

      - name: "Checkout php/doc-en as fallback"
        if: "matrix.language != 'en'"
        uses: "actions/checkout@v2"
        with:
          path: "en"
          repository: "php/doc-en"

      - name: "Revcheck documentation for ${{ matrix.language }}"
        run: "php base/scripts/revcheck.php ${{ matrix.language }} > ./index.html"
      
      - name: "Upload artifact"
        uses: 'actions/upload-artifact@v2'
        with:
            name: ${{ matrix.language }}
            path: ./index.html
  publish:
    name: "Publish on the gh-pages branch"

    runs-on: "ubuntu-latest"
    needs: [setmatrix, rev-check]
    steps:
      - name: Checkout current project
        uses: "actions/checkout@v2"
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./output
      - name: Move file from output directory to parent
        run: |
          mv output/* .
          rmdir output
      - name: Generate the index.html file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: index.html.j2
          output_file: index.html
          strict: true
          data_file: data.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,README.md,index.html.j2,data.json'