name: "Integrate"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  rev-check:
    name: "Revcheck"

    runs-on: "ubuntu-latest"

    # TODO Remove this one
    continue-on-error: true

    strategy:
      matrix:
        language:
          - "de"
          - "en"
          - "es"
          - "fr"
          - "it"
          - "ja"
#          - "pl"
          - "pt_br"
#          - "ro"
          - "ru"
          - "tr"
#          - "uk"
          - "zh"

    steps:
      - name: "Checkout php/doc-base"
        uses: "actions/checkout@v2"
        with:
          path: "base"
          repository: "php/doc-base"

      - name: "Checkout php/doc-${{ matrix.language }}"
        uses: "actions/checkout@v2"
        with:
          path: "${{ matrix.language }}"
          repository: "php/doc-${{ matrix.language }}"

      - name: "Checkout php/doc-en as fallback"
        if: "matrix.language != 'en'"
        uses: "actions/checkout@v2"
        with:
          path: "en"
          repository: "php/doc-en"

      - name: "Revcheck documentation for ${{ matrix.language }}"
        run: "php base/scripts/revcheck.php ${{ matrix.language }} > ./index-${{ matrix.language }}.html"
      
      - name: "Upload artifact"
        uses: 'actions/upload-artifact@v2'
        with:
            name: revcheck ${{ matrix.language }}
            path: ./index-${{ matrix.language }}.html
  publish:
    name: "Publish on the gh-pages branch"

    runs-on: "ubuntu-latest"
    needs: rev-check
    steps:
      - name: Download all the artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./output
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output